_target_: src.datamodules.tau_progression_datamodule_transformer_latest.TauProgressionDataModuleTransformerLatest

##TODO: change params here
data_dir: ${data_dir}
dataset_filename: tau_progression_sequences.csv
split_filename: train_val_test_split_latest.json
batch_size: 32
max_len: 10
num_workers: 0
pin_memory: False
