_target_: src.models.tau_progression_prediction_transformer_full_decoder.TransformerModelFullDecoder

# Given
d_in: 203
d_out: 200

# Tunable
#d_model: 256
#d_hid: 512
#max_len: 10
#n_encoder_heads: 2
#n_encoder_layers: 3
#lr: 0.0001
#activation: "gelu"
#transformer_dropout: 0.25696771128252627
#dropout: 0.010604524216648726
#connectivity_path: ${data_dir}/connectivity.csv

# Tunable
d_model: 128
d_hid: 64
max_len: 10
n_encoder_heads: 2
n_encoder_layers: 8
n_decoder_heads: 8
n_decoder_layers: 2
lr: 0.0001
activation: "gelu"
encoder_dropout: 0.2
decoder_dropout: 0.2
dropout: 0.2

connectivity_path: ${data_dir}/connectivity.csv


