_target_: src.models.components.connectivity_informed_attention.ConnectivityInformedAttention

# Given
d_in: 203
d_out: 200

# Tunable
d_model: 128
d_hid: 100
nheads: 4
lr: 0.0001
activation: "gelu"
dropout: 0.3
connectivity_path: ${data_dir}/connectivity.csv


