_target_: src.models.tau_progression_prediction_transformer_full.TransformerModelFull

# Given
d_in: 403
d_out: 200

# Tunable
#d_model: 256
#d_hid: 512
#max_len: 10
#n_encoder_heads: 2
#n_encoder_layers: 3
#lr: 0.0001
#activation: "gelu"
#transformer_dropout: 0.25696771128252627
#dropout: 0.010604524216648726
#connectivity_path: ${data_dir}/connectivity.csv

# Tunable
d_model: 512
d_hid: 512
max_len: 10
n_encoder_heads: 8
n_encoder_layers: 3
lr: 0.0001
activation: "gelu"
transformer_dropout: 0.2819708330406043
dropout: 0.01099820205599410
connectivity_path: ${data_dir}/connectivity.csv
variable: 0.1


