# @package _global_

# specify here default evaluation configuration
defaults:
  - _self_
  - datamodule: tau_progression_datamodule_transformer.yaml
  - model: tau_progression_prediction_transformer_full_connectome_fusion.yaml
  - callbacks: null
  - logger: null
  - trainer: default.yaml
  - log_dir: evaluation.yaml

  - experiment: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}

data_dir: ${original_work_dir}/data/

print_config: True

ignore_warnings: True

seed: null

name: "connectome_fusion"

# passing checkpoint path is necessary
ckpt_path: /u/home/bue/Documents/connectome-based-tau-spread-prediction/logs/experiments/runs/transformer_full_connectome_fusion/2022-12-19_23-00-39/checkpoints/epoch_083.ckpt
#ckpt_path: /u/home/bue/Documents/connectome-based-tau-spread-prediction/logs/experiments/runs/transformer_full_connectome_fusion/2022-12-19_23-00-39/checkpoints/last.ckpt

#ckpt_path: /u/home/bue/Documents/connectome-based-tau-spread-prediction/logs/experiments/runs/triformer/2023-01-12_17-10-01/checkpoints/epoch_019.ckpt

#ckpt_path: /u/home/bue/Documents/connectome-based-tau-spread-prediction/logs/experiments/runs/multifusion/2023-01-20_07-56-04/checkpoints/epoch_017.ckpt