_target_: src.datamodules.baseline_datamodule.SchaeferDataModule

##TODO: change params here
data_dir: ${data_dir}/ADNI_Tau_Amyloid_SUVR_amyloid_tau_status_dems.csv # data_dir is specified in config.yaml of the parent caller
batch_size: 64
num_workers: 0
pin_memory: False
