_target_: src.datamodules.connectivity_informed_attention_datamodule.ConnectivityInformedAttentionDatamodule

##TODO: change params here
data_dir: ${data_dir}
dataset_filename: tau_progression_sequences.csv
split_filename: train_val_test_split.json
batch_size: 32
num_workers: 0
pin_memory: False
