_target_: src.datamodules.tau_progression_datamodule_transformer.TauProgressionDataModuleTransformer

##TODO: change params here
data_dir: ${data_dir}
dataset_filename: tau_progression_sequences_test.csv
split_filename: train_test_split_test.json
batch_size: 2
max_len: 10
num_workers: 0
pin_memory: False
